## March 3,2026 


# NUMPY


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
arr = np.array(["alpha","beta","gemma"])
print(arr)
print(type(arr))

['alpha' 'beta' 'gemma']
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4))
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr = np.array(43)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
43


In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [19]:
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print (arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [21]:
arr = np.array([1,2,3,4] , ndmin =5)
print(arr)

[[[[[1 2 3 4]]]]]


In [22]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [23]:
arr = np.array([1,2,3,4,6,7,8])
print(arr[2]+arr[4])

9


In [25]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("second elemnt of 1st array",arr[0,1])

second elemnt of 1st array 2


In [27]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,1,2])
print(arr)

6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [30]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5])
print(arr[:3])

[1 2 3]


In [ ]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])