## Numpy Array Explorer

In [2]:

import numpy as np

# 2. Create arrays
A = np.array([2,4,6,8,10,12,14,16,18,20])
B = np.zeros((3,3))
C = np.random.randint(1,101,5)
D = np.linspace(0,5,10)

print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)

# 3. Properties of Array A
print("\n--- Properties of Array A ---")
print("Shape:", A.shape)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Number of Dimensions:", A.ndim)

# 4. Operations on Array A
print("--- Operations on Array A ---")

A_reshaped = A.reshape(2,5)
print("Reshaped Array (2x5):\n", A_reshaped)

max_value = np.max(A)
max_index = np.argmax(A)
print("Max Value:", max_value)
print("Index of Max Value:", max_index)

min_value = np.min(A)
min_index = np.argmin(A)
print("Min Value:", min_value)
print("Index of Min Value:", min_index)

# 5. Create Array E
E = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Array E:", E)

# Element at row 1 column 2
print("Element at row 1 column 2:", E[1][2])

Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [74 57 79 89 58]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

--- Properties of Array A ---
Shape: (10,)
Data Type: int64
Size: 10
Number of Dimensions: 1
--- Operations on Array A ---
Reshaped Array (2x5):
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max Value: 20
Index of Max Value: 9
Min Value: 2
Index of Min Value: 0
Array E: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 column 2: 6
